pull_request_rules:
  - name: 🏷️ Label homework
    description: Label a homework with 'homework' label by detecting keyword
    conditions:
      - body ~= 作业提交
    actions:
      label:
        add:
          - homework
  - name: 🏷️ Label documentation
    description: Label a pull request with 'documentation' label by detecting keyword
    conditions:
      - title ~= ^docs\(.*\)
    actions:
      label:
        add:
          - documentation

  - name: 🏷️ Label enhancement
    description: Label a pull request with 'enhancement' label by detecting keyword
    conditions:
      - title ~= ^feat\(.*\)
    actions:
      label:
        add:
          - enhancement

  - name: 🏷️ Label gh-pages
    description: Label a pull request with 'gh-pages' label by detecting keyword
    conditions:
      - title ~= gh-pages
    actions:
      label:
        add:
          - gh-pages

- name: Debug documentation1
  conditions:
    - title ~= ^docs\(.*\)
  actions:
    comment:
      message: "documentation1 rule matched"

- name: Debug documentation2
  conditions:
    - title~=^docs\(.*\)
  actions:
    comment:
      message: "documentation2 rule matched"

- name: Debug documentation3
  conditions:
    - title~=docs\(.*\)
  actions:
    comment:
      message: "documentation3 rule matched"

- name: Debug documentation4
  conditions:
    - body~=hahaha
  actions:
    comment:
      message: "documentation4 rule matched"
